### ISSUE TITLE
Most examples are broken in 9.4.4.

### ISSUE THREAD

**Issue by liamzee** [composewell/streamly-examples#48]
Some of these won't compile, others seem to be based on broken libraries, etc...

I like streamly very much, but it's much harder to pick up if the examples are guaranteed to be broken.

**Comment by harendra-kumar** [comment]
We do compile all of it quite often and there are CIs as well.

The github repo works with latest streamly. There is a cabal.project.user file that can be used to build it. It may have got broken because of changes in the streamly master branch. We will try to put a specific commit tag in cabal.project to avoid that.

If you want to build examples with released version you can use the latest release tag in this repo or use the hackage version.

There is also a default.nix file that should get consistent versions of dependencies.

We are going to fix it in next few days. Please let's know what specific error you are facing and which ghc version, build method are you using.
